version: "3.9"

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: userinfo
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  python-app:
    build:
      context: .
    container_name: python-app
    depends_on:
      - mysql

volumes:
  db_data:
